# Generated by Django 5.1.7 on 2025-04-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(choices=[('#4285F4', 'Blue'), ('#DB4437', 'Red'), ('#F4B400', 'Yellow'), ('#0F9D58', 'Green'), ('#AB47BC', 'Purple'), ('#00BCD4', 'Cyan'), ('#FF9800', 'Orange'), ('#E91E63', 'Pink'), ('#607D8B', 'Gray')], default='#4285F4', max_length=7)),
                ('start_day', models.CharField(max_length=20)),
                ('end_day', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='boards.calendar')),
            ],
        ),
    ]
